### ISSUE TITLE
How to create a new user with read-only access to the database?

### ISSUE THREAD

**Issue by alexgonca** [alexgonca/opencontractors_database#7]

**Comment by alexgonca** [comment]
CREATE USER guest WITH PASSWORD 'a_password';

GRANT CONNECT ON DATABASE opencontractors TO guest;

GRANT USAGE ON SCHEMA oc_perennial TO guest;

GRANT SELECT ON ALL TABLES IN SCHEMA oc_perennial TO guest;

ALTER DEFAULT PRIVILEGES IN SCHEMA oc_perennial
GRANT SELECT ON TABLES TO guest;

GRANT USAGE ON SCHEMA oc_ephemeral_alpha TO guest;

GRANT SELECT ON ALL TABLES IN SCHEMA oc_ephemeral_alpha TO guest;

ALTER DEFAULT PRIVILEGES IN SCHEMA oc_ephemeral_alpha
GRANT SELECT ON TABLES TO guest;

GRANT USAGE ON SCHEMA oc_ephemeral_beta TO guest;

GRANT SELECT ON ALL TABLES IN SCHEMA oc_ephemeral_beta TO guest;

ALTER DEFAULT PRIVILEGES IN SCHEMA oc_ephemeral_beta
GRANT SELECT ON TABLES TO guest;

GRANT USAGE ON SCHEMA public TO guest;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO guest;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO guest;

**Comment by riordan** [comment]
It makes me very happy you’re still working on this project

**Comment by alexgonca** [comment]
Hi David, it is great to hear from you! :)

In fact, the project became less relevant since usaspending.gov started making the original database behind usaspending available as a PostgreSQL archive:
https://files.usaspending.gov/database_download/
That was the need that we were trying to fill.

Now our project is useful to help people understand the internal structure of the usaspending database.
